### ISSUE TITLE
Issue while Running Code iosynth

### ISSUE THREAD

**Issue by shashwatwork** [rradev/iosynth#2]
Hi,
I got the following error while running iosynth with configurations mentioned in Readme.md file.
![Capture](https://user-images.githubusercontent.com/22785727/56509698-52559500-6545-11e9-8b1b-c79ed5720568.PNG)
I successfully build the maven and ran the code with the latest jar files.

Please help me out with this error as I am not able to catch it, also pls clarify the process to run iosynth briefly.

Thanks,
Shashwat

**Comment by jegb** [comment]
did you set the classpath?
`$ export CLASSPATH=/home/iosynth-0.0.7.jar`
